food-app/food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    path("food/", views.IndexClassView.as_view(), name="index" ),
    path("<int:pk>/", views.DetailsClassView.as_view(), name="details" ),
    path("add/", views.CreateItemClassView.as_view(), name="create_item" ),
    path("update/<int:itemId>/", views.updateItem, name="update_item" ),
    path("delete/<int:itemId>/", views.deleteItem, name="delete_item" ),
]

food-app/food_app/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path("profile/", user_views.profilePage, name="profile"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food-app/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.IntegerField()
    image = models.CharField(max_length=500, default= "https://placehold.co/600x400?text=Food")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self) -> str:
        return self.name 

    def get_absolute_url(self):
        return reverse("food:details", kwargs={"pk": self.pk})
    

food-app/users/models.py
from django.db import models
from django.forms import CharField
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username 

food-app/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ["name", "description" , "price", "image"] 

food-app/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterFrom(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

food-app/food/views.py
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template import loader
from food.forms import ItemForm
from food.models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# # Create your views here.
# def index(request):
#     itemLIst = Item.objects.all()
#     context = {
#         "items": itemLIst,
#     }
#     return render(request=request, template_name="food/productsList.html", context=context)

# class base view
class IndexClassView(ListView):
    model = Item;
    template_name = "food/productsList.html"
    context_object_name = "items"

# def itemDetails(request, itemId):
#     item = Item.objects.get(id=itemId)
#     context = {
#         "item": item,
#     }
#     return render(request=request, template_name="food/details.html", context=context)

class DetailsClassView(DetailView):
    model = Item
    template_name = "food/details.html"
    context_object_name = "item"

# def createItem(request):
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()

#         return redirect("food:index")
#     return render(request, "food/create-item-form.html", 
#         {
#         "form": form
#         })

class CreateItemClassView(CreateView):
    model = Item
    fields = ["name", "description", "price", "image"]
    template_name = "food/create-item-form.html"

    def formValid(self, form):
        form.instance.user = self.request.user
        return super().formValid(form)

def updateItem(request, itemId):
    item = Item.objects.get(id=itemId)

    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")

    return render(request, "food/create-item-form.html", 
        {
        "form": form,
        "item": item
        })

def deleteItem(request, itemId):
    item = Item.objects.get(id=itemId)

    if request.method == "POST":
        item.delete()
        return redirect("food:index")

    return render(request, "food/details.html", 
        {
            "item": item,
        })

food-app/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import RegisterFrom

# Create your views here.

def register(request):
    # si la petición es post entonces crear el usuario
    if request.method == "POST":
        # cargar el formulario personalizado
        form = RegisterFrom(request.POST)
        # verificar que el formulario es valido
        if form.is_valid():
            # guardar el usuario en la base de datos
            form.save()
            # redirigir a la pagina de inicio
            return redirect("login")

    else:
        # en caso de que la petición sea un GET entonces renderizar la pantalla del formulario
        form = RegisterFrom()

    return render(request, "users/register.html",
        { 
            "form": form
        })

@login_required
def profilePage(request):
    return render(request,"users/profile.html" )

food-app/food/templates/food/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
	<head>
		<title>Food Page</title>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no" />

		<!-- Bootstrap CSS v5.2.1 -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
			crossorigin="anonymous" />
	</head>

	<body>
		<header>
			<!-- place navbar here -->
			<nav
				class="navbar navbar-expand navbar-dark bg-dark container d-flex justify-content-between px-3 px-sm-0">
				<div class="navbar-brand">
					<a href="/food" class=" nav-link">FoodApp</a>
				</div>
				<div class="nav navbar-nav">
					<a
						class="nav-item nav-link"
						href={% url 'food:create_item' %}
						>Add Item</a
					>
					<a class="nav-item nav-link" href="/admin">Admin</a>

					{% if user.is_authenticated %}
						<a class="nav-item nav-link" href="/profile">My account</a>
						<form action="{% url 'logout'%}" method="POST">
							{% csrf_token %}
							<button class="nav-item nav-link" href="/logout">Log out</button>
						</form>

					{% else %}
						<a class="nav-item nav-link" href="/login">Log in</a>

					{% endif %}
				</div>
			</nav>
		</header>
		<main class="container p-5 py-sm-5 px-sm-0">
			{% block body %} {% endblock %}</main>
		<footer>
			<!-- place footer here -->
		</footer>
		<!-- Bootstrap JavaScript Libraries -->
		<script
			src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
			integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
			crossorigin="anonymous"></script>

		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
			integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
			crossorigin="anonymous"></script>
	</body>
</html>

food-app/food/templates/food/create-item-form.html
{% extends "food/base.html" %} {% block body %}
<form method="POST">
	{% csrf_token %} {{ form }}
	<button class="btn btn-primary" type="submit">Save</button>
</form>
{% endblock %}

food-app/food/templates/food/delete-item.html
<!-- Modal Body -->
<!-- if you want to close by clicking outside the modal, delete the last endpoint:data-bs-backdrop and data-bs-keyboard -->

<form method="POST" action={% url 'food:delete_item' item.id %}>
	{% csrf_token %}
	<div
		class="modal fade"
		id="modalDelete"
		tabindex="-1"
		data-bs-backdrop="static"
		data-bs-keyboard="false"
		role="dialog"
		aria-labelledby="modalTitleId"
		aria-hidden="true">
		<div
			class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-sm"
			role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modalTitleId">Are you sure?</h5>
				</div>
				<div class="modal-body">
					<p>You are going to delete item: {{ item.name }}</p>
				</div>
				<div class="modal-footer">
					<button
						type="button"
						class="btn btn-secondary"
						data-bs-dismiss="modal">
						Cancel
					</button>
					<button
						class="btn btn-danger"
						type="submit">
						Delete
				</button>
				</div>
			</div>
		</div>
	</div>
</form>

food-app/food/templates/food/details.html
{% extends "food/base.html" %} {% block body %}
{% include "food/delete-item.html" %}
<div class="row container">
	<div class="col ratio ratio-4x3">
		<img src="{{ item.image }}" class="img-fluid rounded-2 object-fit-cover" alt="" />
	</div>
	<div class="col d-flex flex-column py-2">
		<div class="h-100">
			<h2>{{ item.name }}</h2>
			<p>{{ item.description }}</p>
			<p>$ {{ item.price }}</p>
			
		</div>
		<div>
			<a href={% url "food:update_item" item.id %} class="btn btn-success col">Edit</a>
			<button class="btn btn-danger col" type="button" data-bs-toggle="modal" data-bs-target="#modalDelete">Delete</button>
		</div>
	</div>
</div>
{% endblock %}

food-app/food/templates/food/productsList.html
{% extends "food/base.html" %} {% block body %}

<div
	class="row row-cols-lg-5 row-cols-md-4 row-cols-1 column-gap-4 justify-content-center gap-3">
	{% for item in items %}
	<div class="card col">
		<div class="card-body">
			<div class="ratio ratio-4x3">
				<img
					src="{{ item.image }}"
					class="rounded-2 img-fluid object-fit-cover" />
			</div>
			<p class="card-title text-nowrap fw-bold fs-5">{{ item.name }}</p>
			<p class="card-text text-truncate">{{ item.description }}</p>
			<p class="card-text">$ {{ item.price }}</p>
			<a
				class="card-text btn btn-primary"
				href="{% url 'food:details' item.id %}"
				>Go to details</a
			>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

food-app/users/templates/users/login.html
{% extends "food/base.html" %} {% block body %}
<form method="POST">
	{% csrf_token %} {{ form }}
	<button type="submit">Login</button>
</form>
{% endblock %}

food-app/users/templates/users/logout.html
<div class="container">
	<p>You have been log out</p>
</div>

food-app/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" />

food-app/users/templates/users/register.html
{% extends "food/base.html" %} {% block body %}

<form method="POST">
	{% csrf_token %} {{ form }}
	<button type="submit">Signup</button>
</form>
{%endblock %}